sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 秘密
  alioss:
    endpoint: 秘密
    access-key-id: 秘密
    access-key-secret: 秘密
    bucket-name: 秘密


