sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 456852
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tGmRHRP2n5mdbv9JUCg
    access-key-secret: jqRiF1CL5darreUIM39alONK04H942
    bucket-name: zn-cu


